### ISSUE TITLE
Request: Font-settings

### ISSUE THREAD

**Issue by JayVii** [nuclearfog/Shitter#10]
Using Version 1.6

It would be really nice to have some further font-settings, apart from colour. I am currently using a black background colour and white font, however it is extremely hard to read tweets, when the screen is not on full brightness.

This is mainly caused by the light font type in use and could be solved by either giving the option to use another font-type (e.g. **bold**) and/or giving the option to use bigger fontsize.

Thanks for developing the app, i am looking forward to what comes next :)

**Comment by nuclearfog** [comment]
Thanks for your suggestion, I will add this function in the next version

**Comment by nuclearfog** [comment]
I have finished implementing font options. Version 1.7.1 is online!
