### ISSUE TITLE
(Feature Request) Implement 'favoriting' Of Posts

### ISSUE THREAD

**Issue by puppykickr** [nuclearfog/Shitter#11]
I have noticed that recent updates have yet to include adding the ability to 'favorite' posts and comments.

Will this feature be added anytime soon?
It seems to me to be a big part of participation on the site.

Great app otherwise, though.
Thank you for your work on it.

**Comment by nuclearfog** [comment]
Thank you, @puppykickr You can favorite or retweet a post by long clicking the buttons.

**Comment by puppykickr** [comment]
@nuclearfog 
Oh, cool!
Here I have been tapping it and getting a toast message that it has not been implemented yet!

It never dawned on me to long press it.
So, I just tried it and it works perfect.

The favorite and retweet is even faster than when I use a browser.

And the theme adjustment is awesome.

So much better on the eyes!

Not to mention the hilarious name...
