### ISSUE TITLE
Translation needed!

### ISSUE THREAD

**Issue by nuclearfog** [nuclearfog/Shitter#12]
SHITTER currently supports german and english. Any help for adding more languages is highly welcomed!

**Comment by Kiroc** [comment]
How can I help with translations?

**Comment by nuclearfog** [comment]
If you're using Android Studio, you can simply add a new translation 

![android_studio_translation_editor](https://user-images.githubusercontent.com/32868976/94988673-45790580-056f-11eb-88ff-b9da90c43843.png)

**Comment by shuvashish76** [comment]
I've seen OSS projects use these sites for translation purpose
- [Crowdin](https://crowdin.com/)
- [Transifex](https://www.transifex.com/)
- [Weblate](https://weblate.org/en/)

I think Weblate is better as it's [opensource](https://github.com/WeblateOrg/weblate).

Features: https://weblate.org/en/features/
![Screenshot_2021-12-05-21-15-09](https://user-images.githubusercontent.com/48226312/144753433-4fc61e84-f12d-42d0-885e-1b9abd399061.jpeg)
https://weblate.org/en/hosting/

**Comment by DallasBelt** [comment]
I can help with Spanish (South America).

**Comment by nuclearfog** [comment]
I have created a new [folder](https://github.com/nuclearfog/Shitter/tree/master/app/src/main/res/values-es)  for spanish translation. You can edit the resource files.
