### ISSUE TITLE
Can't sent tweet with photo

### ISSUE THREAD

**Issue by wazlecracker** [nuclearfog/Shitter#13]
Using your app on GrapheneOS 2020.08.07.01, app version 1.7.11 installed from the IzzyOnDroid repo.

I'm trying to send a tweet to a dev with an attached screenshot, but when I press send I get the "Error! error while sending" pop up and a toast at the bottom of my screen which says "File not found". I've made sure to give the app storage permissions.

**Comment by nuclearfog** [comment]
Thanks for the info! I will fix it soon

**Comment by nuclearfog** [comment]
I have fixed the issue! Version 1.7.12 is released
