### ISSUE TITLE
The problem of get PIN on Android 4.4.2

### ISSUE THREAD

**Issue by AlbahrawyAlalimi** [nuclearfog/Shitter#14]
When you press the get PIN button, it waits for a second while using 1kb of mobile data, then a message appears at the bottom of the screen, "connection failed!" Knowing that there is no problem in communicating with other applications.

**Comment by nuclearfog** [comment]
That's because Twitter dropped support for TLS 1.1. Android 4.x devices can't access Twitter API anymore.
