### ISSUE TITLE
Get Pin Button Doesn't Work

### ISSUE THREAD

**Issue by emmatebibyte** [nuclearfog/Shitter#16]
On Android 10 on my Samsung Galaxy A50, the Get Pin button does nothing.

**Comment by nuclearfog** [comment]
Sometimes it takes long to get the request link from Twitter. I've added a feedback when requesting the link


<img src="https://user-images.githubusercontent.com/32868976/95685459-4c9bb580-0bf8-11eb-84bc-10c11ad0c810.png" width="360"/> <img src="https://user-images.githubusercontent.com/32868976/95685554-d8154680-0bf8-11eb-9588-57aa74897d18.png" width="360"/>
