### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by frunkAF** [nuclearfog/Shitter#21]
I'm using version 1.8.5 from F-Droid. A couple of hours ago it stopped working and I was prompted to log in again. I cleared data and logged in via web browser to make sure the account wasn't locked. I'm in the initial (1.2.3) setup and when I hit (1. get PIN) I get a message saying "redirecting to twitter login". After a couple of seconds, I get a message saying "can't login to twitter. Please re-login". Is this a user error on my part or is something no working right now?

**Comment by frunkAF** [comment]
Update: I installed version 1.8.6 from the releases and now in getting a 403 error.

I looked it up and apparently it has to do with daily usage limits for twitter accounts but this is before I even login. is there a daily usage limit for authorizing apps or something?

**Comment by nuclearfog** [comment]
Sorry for this but Twitter has locked my app because someone uses my API keys for spaming, so I had to change them. I have written to the support to unlock my app.

**Comment by nuclearfog** [comment]
It's working now. Please update to the latest version.
