### ISSUE TITLE
How to search?

### ISSUE THREAD

**Issue by NitroNils** [nuclearfog/Shitter#26]
Hi, in the UI I can't seem to locate a search function - I've checked the description which mentions "twitter search".

**Comment by nuclearfog** [comment]
Hey
You can simply search if you swipe to the trends tab and click on the search icon.

<img src="https://user-images.githubusercontent.com/32868976/106217799-56145200-61d6-11eb-82d6-18fd1fe24a30.jpg" width="250"/> <img src="https://user-images.githubusercontent.com/32868976/106217842-69272200-61d6-11eb-89a1-c7aed4a6d058.jpg" width="250"/>
