### ISSUE TITLE
Trying to authorized app fails 

### ISSUE THREAD

**Issue by ruralTom** [nuclearfog/Shitter#33]
When you put your info to authorize the app (on Twitter's website) results in a page not found error.

This is likely their issue, but thought I'd let you know  in case your api got dinked again.

**Comment by nuclearfog** [comment]
Thank you for the information, I have checked the login and it works for me. I think it is a Twitter bug when the website doesn't return to the PIN page after login.

**Comment by ruralTom** [comment]
@nuclearfog You are correct. Found out this morning they locked my account for strange activity. Their automated security gets pissy about my VPN usage.

**Comment by nuclearfog** [comment]
Yes, this happened to me too when using TOR browser. Sometimes you have to login over the website and solve some captchas

**Comment by Blake-LeBlanc** [comment]
This is happening to me after reinstalling the app. I click "Get PIN", it gives notice it's redirecting to Twitter login, but nothing happens. And a while later, there's another notice saying "Connection failed".

Anything I can do on my end to resolve this @nuclearfog ?

I logged into Twitter and revoked the app's permissions, hoping it would "force" it to go through the authentication process again
