### ISSUE TITLE
Links not showing up in clicked tweets

### ISSUE THREAD

**Issue by ruralTom** [nuclearfog/Shitter#38]
When you look at a tweet in a feed, you can see a link, but when you tap the tweet,  linky go bye bye.

I've attached photos!

![See the url](https://i.imgur.com/P9SzUGv.jpg)

![Clicked it](https://i.imgur.com/LGyofxC.jpg)

![Not in the photo. ](https://i.imgur.com/7ytVvct.jpg)

Weird right?

**Comment by nuclearfog** [comment]
Can you scroll the tweet text?

**Comment by ruralTom** [comment]
Son of a....

Disregard. Apparently I need a nap. Or a CAT scan...

Dec 18, 2021 1:13:05 AM nuclearfog ***@***.***>:
