### ISSUE TITLE
Redirect after authorize does not redirect to app

### ISSUE THREAD

**Issue by kgorol** [nuclearfog/Shitter#39]
I have behaviour like on video below.

https://user-images.githubusercontent.com/34159482/147870003-dbef7003-c4d5-4724-a14c-279910458798.mp4

**Comment by nuclearfog** [comment]
I have fixed it in the latest release (version 1.10.6)

**Comment by kgorol** [comment]
Thanks, it works now! Stupid question, how do I access app settings after login?
