### ISSUE TITLE
Proxy does not work。

### ISSUE THREAD

**Issue by lukemin** [nuclearfog/Shitter#4]
I deployed squid on my vps.
Telegraph can connect to server, but shitter didnot.
The toast showed that Connection reset!!
Proxy type is HTTP, and need user name and password.

**Comment by nuclearfog** [comment]
Shitter uses only HTTPS connections because of twitter API.

**Comment by lukemin** [comment]
what  about socks5?

**Comment by nuclearfog** [comment]
Sorry, but there is no other way
