### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by shuvashish76** [nuclearfog/Shitter#40]
I see the app is already available on [izzy-repo](https://apt.izzysoft.de/fdroid/index/apk/org.nuclearfog.twidda) (#5)

Would you consider putting this app on F-Droid, please?
Thank you.

**Comment by Poussinou** [comment]
Would it be possible to store them in the source code in this repo? (probably like [Twidere](https://github.com/TwidereProject/Twidere-Android) did it)

**Comment by nuclearfog** [comment]
I am responsible for my API keys so I have to protect them from abuse. A year ago my app got suspended because of this. The only way to put this app on F-Droid is without API keys.

**Comment by Cwpute** [comment]
I can confirm that it is now available in F-Droid :)
![Screenshot_20230707-011840](https://github.com/nuclearfog/Shitter/assets/80604512/1a597800-afff-4450-aa33-618e24acc0a1)
