### ISSUE TITLE
No comments under tweets

### ISSUE THREAD

**Issue by reachrishav** [nuclearfog/Shitter#42]
On clicking a tweet only the primary tweet shows and not the comments, which I guess is more helpful.

**Comment by nuclearfog** [comment]
Twitter API doesn't have any endpoint to get tweet replies direclty. The only solution is to use search endpoint, which only returns replies up to one week. I'll fix this if Twitter adds this endpoint.

**Comment by reachrishav** [comment]
> Twitter API doesn't have any endpoint to get tweet replies direclty. The only solution is to use search endpoint, which only returns replies up to one week. I'll fix this if Twitter adds this endpoint.

@nuclearfog could you please add the temporary workaround using search endpoint for the time being?
