### ISSUE TITLE
Update: crash on opening 2.2 to 3 alpha

### ISSUE THREAD

**Issue by franco27** [nuclearfog/Shitter#49]
hello

I had installed a 2.x version to 2.2.
When I installed version 3 alpha, I couldn't open the app anymore. A crash each time I opened it, I couldn't see the window.
may be due to user data.

I had to uninstall and reinstall. After reinstalling version 3, without updating, I can now open without immediate closing by clicking on the icon.

**Comment by nuclearfog** [comment]
I have fixed this bug in the new release.

**Comment by franco27** [comment]
👍
