### ISSUE TITLE
Please increase versionCode

### ISSUE THREAD

**Issue by IzzySoft** [nuclearfog/Shitter#5]
Please do not forget to always increase `versionCode` whenever you release a new version. Currently, it's still set to `1`.

Background: `versionCode` is what Android uses to tell versions apart and decide which is newer; `versionName` is mostly a human-readable representation. So currently, all versions of Shitt3r would be considered the same, which makes updating a bit harder.

**Comment by nuclearfog** [comment]
Thank you for the tips! I'll update the app

**Comment by IzzySoft** [comment]
Cool, thanks!

Btw: I've made your app available via my repo (see [here](https://apt.izzysoft.de/fdroid/index/apk/org.nuclearfog.twidda)), so it can be installed and updated using the F-Droid client. Updates will show up there within 24h of your attaching them to a new tag (so 1.5.4 should show up there in about 6 hours with the next sync). Hope that's OK with you; be welcome to point there.

**Comment by nuclearfog** [comment]
That's great, thank you :)

**Comment by IzzySoft** [comment]
Anytime! Thanks for providing your app free and with source!
