### ISSUE TITLE
Twitter API access blocked

### ISSUE THREAD

**Issue by nuclearfog** [nuclearfog/Shitter#50]
Hello,

Twitter has limited my API access... Some functions will be not available. I'm working for a solution. Maybe I have to regenerate the API tokens so all previous versions will not work anymore. 

![IMG_20221227_174732](https://user-images.githubusercontent.com/32868976/212409854-3d06d655-470a-4ba0-b1c0-e3ba34c9bf78.jpg)

**Comment by nuclearfog** [comment]
If Twitter unlock my API access, I'll release version 3.0 with the new API keys ASAP. Sorry for the inconvenience.

**Comment by Rizby** [comment]
How to will take to fix the issue?

**Comment by Rizby** [comment]
How much time will it take to fix the issue?

**Comment by nuclearfog** [comment]
I have opened a support ticket. I think it will take at least one week.

**Comment by Vilianexe** [comment]
> If Twitter unlock my API access, I'll release version 3.0 with the new API keys ASAP. Sorry for the inconvenience.

nah bro, it's fine, thank you for your work

**Comment by Symbian9** [comment]
Not sure where its new issue or not, but it seems like a lot of 3d party clients mass banned to access Twitter's API since today:

- Thread on HN: https://news.ycombinator.com/item?id=34363743
  - 3rd party clients status: https://docs.google.com/spreadsheets/d/1O27Co27g2fWRon7gK79R8e4th6Xtort3bm289_2jhjQ/edit

Just tried to login in Twitter with latest *Shitter* `3.0` (clean install), but on "get code" step got notification *"API does not support this operation!"*.

**Comment by nuclearfog** [comment]
I have tested the API access with Postman. Everthing works except write actions and login.

**Comment by Symbian9** [comment]
> I have tested the API access with Postman. Everthing works except write actions and login.

Has You tried to make clean install of  Shitter on real device and login to Twitter today?

**Comment by Symbian9** [comment]
> Everthing works except write actions and login.

I just wonder why *Twidere*¹ stopped to work today, but *TwidereX*² still works:

1. https://github.com/TwidereProject/Twidere-Android
2. https://github.com/TwidereProject/TwidereX-Android

**Comment by nuclearfog** [comment]
There are some problems with the Twitter API since months.

**Comment by Symbian9** [comment]
> There are some problems with the Twitter API since months.

I mean, that according latest mass block of many 3rd party apps, Twidere blocked but TwidereX is not — what is a difference in those two apps from same developer in handling Twitter's login & API?

Could be TwidereX way of handling API used in Shitter?

**Comment by nuclearfog** [comment]
I think it's because Twidere uses API version 1.1 which is more reliable than the latest API version 2.0.

**Comment by Dansh01** [comment]
Can you fix it pls?

**Comment by Symbian9** [comment]
Twitter API could not be used by 3rd party apps in legal way anymore:

- https://www.theverge.com/2023/1/19/23562947/twitter-third-party-client-tweetbot-twitterific-ban-rules

**Comment by nuclearfog** [comment]
I have created a new app access. It's working now but API version 2.0 isn't supported.

![Screenshot_20230120_165340](https://user-images.githubusercontent.com/32868976/213744249-3a5d5541-e085-40e9-b20b-284ecc33c81d.png)

**Comment by Dansh01** [comment]
I checked it, it's working! Though some functions are still not working like l am not able to see the comments

**Comment by nuclearfog** [comment]
Version 3.0.2 should work now.

**Comment by nuclearfog** [comment]
The Twitter API access is blocked again...

![Screenshot_2023-01-25-22-26-31-77_ed7821ed99ee442dec4ede205e7971d6](https://user-images.githubusercontent.com/32868976/214694928-8b61827b-69f1-4ca8-a5d1-7f88f209bc00.jpg)

**Comment by west89** [comment]
It got better after the 3.0.2 update.
https://user-images.githubusercontent.com/42120960/215328984-e564cab6-d7c9-429e-9994-ec0d89eb6dbb.mp4

**Comment by nuclearfog** [comment]
Twitter has blocked the login endpoints. There is no way to use the default keys. Every free app is affected by the latest decision of Twitter.

**Comment by 7eter** [comment]
maybe phrasing twitter like [fritter](https://fritter.cc/) does is an option?
