### ISSUE TITLE
App crash after Login to Mastodon (App can't be reopen)

### ISSUE THREAD

**Issue by skdubg** [nuclearfog/Shitter#51]
hi,

after a new fresh install of Shitter 3.0 there is no working with Mastodon possible.
the App crashes after closing it. it can't be reopen again.

Device is a Moto G82 5G with Original Android 12

**Comment by nuclearfog** [comment]
I have created a new release: https://github.com/nuclearfog/Shitter/releases/tag/3.0 Can you check if it is fixed @skdubg ?

**Comment by skdubg** [comment]
yes it works 👍 thank you

**Comment by nuclearfog** [comment]
Thank you for your help 🙏🏼
