### ISSUE TITLE
get code button doesn't work?

### ISSUE THREAD

**Issue by griffi-gh** [nuclearfog/Shitter#52]
It shows a "Redirecting to Twitter login website" toast but then nothing happens

**Comment by nuclearfog** [comment]
It is because Twitter blocked API access of many apps #50

**Comment by griffi-gh** [comment]
oh didn't know about that

**Comment by franco27** [comment]
I too have this problem.
for Twitter when I click on the button nothing happens

**Comment by franco27** [comment]
Quand je clique sur le bouton il n'y a aucune fenêtre qui s'affiche. le navigateur Internet ne s'ouvre pas.
pourtant d'autres applications Twitter fonctionne toujours.

**Comment by nuclearfog** [comment]
The Twitter API access is still blocked. I have contacted the support but still no answer.
