### ISSUE TITLE
issues with login on mastodon instances other than mastodon.social

### ISSUE THREAD

**Issue by Fauli1221** [nuclearfog/Shitter#53]
Login on other instances then the mastodon.social instance seems kinda impossible 

The settings menu doesn't work when changing the instance url it still redirects me to mastodon social when I press the get key button 

I have version 3.0.3 from Izzy on droid F-Droid repo

**Comment by nuclearfog** [comment]
I have fixed this bug in version 3.0.4

**Comment by Fauli1221** [comment]
Yep issues fixed in the new update thanks
