### ISSUE TITLE
Setup for Twitter account

### ISSUE THREAD

**Issue by soumyaDghosh** [nuclearfog/Shitter#57]
How to setup the twitter account in this app? I'm not understanding it. Please help.

**Comment by nuclearfog** [comment]
Hello,
If you have a working Twitter API access with oauth tokens, you can add them in the login page:

![IMG_20230421_000421](https://user-images.githubusercontent.com/32868976/233497709-a12a9424-7b3b-4f8e-ab1a-8a543c54212c.jpg)
![IMG_20230421_000611](https://user-images.githubusercontent.com/32868976/233497743-3045411c-d6b0-4324-a3e9-efed7d0a7f7f.jpg)
