### ISSUE TITLE
Suggestion for a name change

### ISSUE THREAD

**Issue by Martinligabue** [nuclearfog/Shitter#59]
Hi there! I wanted to suggest that the name “Shitter” may be somewhat weird since it has a negative connotation in English. I understand that the name may have a different meaning in other languages, but I think it could be confusing or off-putting for English-speaking users. I would like to suggest that the name be changed to something more neutral or positive.

**Comment by nuclearfog** [comment]
Yes, it is because this app was a Twitter client before. The name "Shitter" is a parody to the name "Twitter". Now, after Twitter blocked all 3rd party apps, it makes no sense to keep this name.
I am open to new name proposals but there are some problems:
- App icon and graphics
- most users know this app as "Shitter". Maybe there will be some trouble after renaming

**Comment by Lightsockie** [comment]
Mastodon is sorta close sounding to masturbation, bet theres some angle that can be worked there. "Mastordation"? Or maybe just " Shitterdon"?

**Comment by xxxcrow** [comment]
Competition for the worst name ever begins!

**Comment by Cwpute** [comment]
I'm sorry but if @Martinligabue 's request is specifically to avoid being off-putting, i don't think that names referencing masturbation or feces would be a good idea, would it ? 🤡

**Comment by Cwpute** [comment]
I'd suggestLyuba, as it is the name given to a baby mamoth miraculously preserved in ice:https://en.wikipedia.org/wiki/Lyuba_(mammoth)

Since this app is supposed to be lightweight, small… i figured a baby mammoth could share its name.

**Comment by Martinligabue** [comment]
(If another name changes the identity of the app too much, it might be a good idea to keep the same idea behind the name, and at least make it clear that it's not about Twitter, but about Mastodon)

**Comment by nuclearfog** [comment]
I think it would be good to change only some letters and keep the initial letters of the old name, so it is easier to find. I don't know if changing the repository name would affect fdroid.
@Martinligabue

**Comment by Cwpute** [comment]
Thinking about the Jurassic Park scene: https://www.washingtonpost.com/news/speaking-of-science/wp/2018/06/22/jurassic-park-put-dino-dung-on-the-silver-screen-heres-the-real-poop/

"Coprolite" or "Coprolight"

litterally: fossilized dung. also a nod to mammoth, and the old unpractical, dying service that is(was) twitter

**Comment by catfromplan9** [comment]
Keep the name as is

**Comment by nuclearfog** [comment]
Yes, changing app name, repo name and graphics is too much. Maybe in the future, but I can add an option to change API name.
