### ISSUE TITLE
Register as default twitter client

### ISSUE THREAD

**Issue by dangyou** [nuclearfog/Shitter#6]
Shitter can be set as a default application when asked to open something in twitter instead of browser whereas the uri pointing at:
Twitter.com*
Or register itself as new default handler
Something like the following articles:
https://stackoverflow.com/questions/21088250/android-launch-twitter-intent

https://developer.android.com/guide/topics/permissions/default-handlers

**Comment by nuclearfog** [comment]
Currently Shitter can only open links to tweets. I'm looking for a better solution

**Comment by nuclearfog** [comment]
I've finished working on deep links. You can now open tweets, user profiles and search page.
