### ISSUE TITLE
update screenshot from repository

### ISSUE THREAD

**Issue by nuclearfog** [nuclearfog/Shitter#60]
Hello @IzzySoft 

can you update the screenshots in this repository?
https://apt.izzysoft.de/fdroid/index/apk/org.nuclearfog.twidda

**Comment by IzzySoft** [comment]
Theoretically I can. Practically I never know when. How about you adding them to your fastlane structure? They'd belong to `fastlane/metadata/android/en-US/images/phoneScreenshots/`. Whatever is in that structure will be pulled along with each new release, once I've enabled it on my end – so you'd simply had to place new screenshots there, and everything else goes automatically.

Just let me know when they're there, and I'll take care for the rest.

**Comment by nuclearfog** [comment]
I can add them to fastlane structure

**Comment by nuclearfog** [comment]
I have moved the screenshots to fastlane folder

**Comment by IzzySoft** [comment]
Needs to be one level deeper, inside `images/` :wink:

**Comment by nuclearfog** [comment]
I have moved the screenshots to image folder c0fe70e46724e88d792b888e2d8711338cfcf0a6

**Comment by IzzySoft** [comment]
Thanks! Updated the config, manually triggered a fastlane pull – screenshots came along. The next sync should reflect that – and the same of course for future updates.

All done I'd say, issue solved – thanks a lot for your help with this!
