### ISSUE TITLE
Feature list shows real timelines (chronological order) - but timeline only displays in reverse order

### ISSUE THREAD

**Issue by StuBouyer** [nuclearfog/Shitter#64]
The feature list has **real timelines (chronological order)** listed, however the timeline only displays in reverse chronological order (like Twiiter or Facebook) with new posts the top.

Chronological order would oldest post first and we would scroll down to see new posts. This would make reading long posts easier.

Am I missing something in the settings to switch to true chronological order?

**Comment by nuclearfog** [comment]
No it's reverse chronical. It's my fault, I'll change this

**Comment by StuBouyer** [comment]
That's a shame, I got excited because that's what I'm looking for in a mastodon app

**Comment by nuclearfog** [comment]
I can implement this in the future
