### ISSUE TITLE
Viewing threads.

### ISSUE THREAD

**Issue by pygopero** [nuclearfog/Shitter#66]
As long as I have seen. It is not possible to see the whole thread that a toot take part of. You only can see the direct toot that is replied, and the direct replies that the current toot has provoked, but it is not possible to read the whole thread with all the previous toots and all the followings.
¿Maybe is that behavior intended?

**Comment by nuclearfog** [comment]
Yes, it was intended in the past because Twitter didn't support threads (only direct replies). Now I have fixed it 84e2938c903c26e7af4db0a513c981b6f9ec8fd5
