### ISSUE TITLE
[BUG] can't like or boost posts

### ISSUE THREAD

**Issue by raphaelsiz** [nuclearfog/Shitter#67]
**Describe the bug**
I can't tell if this is actually a bug or simply a feature that hasn't been implemented, but I can't like or boost posts.

**To Reproduce**
1. Go to your home or any other timeline with posts in it
2. Click on the like or repost button of a post
3. See (potential) bug: this opens the page of the post as if you had clicked on the text of the post
4. Click on the like or repost button
5. See (potential) bug: this shows who has liked or reposted the post

**Expected behavior**
I expected either clicking the like/boost icon on the timeline, or clicking the like/boost icon on the post page, to like/boost the post. Preferably both, but at least one way to do it. Considering the reply button on the post page does lead to replying to the post, it would make sense for its analogous buttons to work in an analogous way

**Screenshots**
![Screenshot_2024-01-10-18-39-57-42_442f07617ccab621ddda2d75b1eea98e](https://github.com/nuclearfog/Shitter/assets/64447714/e22b6cf6-3840-4e61-bef0-801e1a17272b)
![Screenshot_2024-01-10-18-41-35-90_442f07617ccab621ddda2d75b1eea98e](https://github.com/nuclearfog/Shitter/assets/64447714/a455aca4-e449-45e1-ac0e-0a23d803e83e)

**Logcat**
If applicable, add a Logcat output (only of this app!) see: https://developer.android.com/tools/logcat

**Smartphone (please complete the following information):**
 - OS: Android 12
 - App Version: 3.5.3

**Additional context**
Just that replying seems to work

**Comment by nuclearfog** [comment]
You can like/boost a post when you keep the button pressed for one second.
