### ISSUE TITLE
Fix F-droid description - lines

### ISSUE THREAD

**Issue by inson1** [nuclearfog/Shitter#69]
![Screenshot_2024-02-18-10-05-28-261_org.fdroid.fdroid.jpg](https://github.com/nuclearfog/Shitter/assets/75314629/1633c6e3-de31-4e05-9e07-131f3175ed22)

**Comment by nuclearfog** [comment]
fixed a28061245a951418e2ff8fcd165b08f55ca0d183

**Comment by inson1** [comment]
@nuclearfog maybe there shoulnt be also line between features and feature list
