### ISSUE TITLE
APK of last release unsigned?

### ISSUE THREAD

**Issue by IzzySoft** [nuclearfog/Shitter#7]
It looks like you forgot to sign the APK attached to v1.5.5 – at least it has no v1 signature:

```
$ apksigner verify SH1TT3R.apk
DOES NOT VERIFY
ERROR: No JAR signatures
```

Which means it won't install on Android versions before Nougat, as those don't know anything about v2 signatures. Could you please check and fix? Thanks!

(PS: yes, you can sign both v1 and v2 similarly, and even v3 on top, those signatures won't conflict)

**Comment by nuclearfog** [comment]
Thanks I've fixed it.

**Comment by IzzySoft** [comment]
Thanks a lot, confirmed!
