### ISSUE TITLE
[Feature request] App is not using screen real estate

### ISSUE THREAD

**Issue by andreas1107** [nuclearfog/Shitter#70]
**Describe the bug**
There is more screen space than the app is using. 

**To Reproduce**
Open a long-ish Mastodon post. See the large unused part of screen.

**Expected behavior**
The full post is shown, and if it's too long to fit on the screen, the user can scroll down. 

**Screenshots**

![Screenshot_20240219-190737_Shitter_1](https://github.com/nuclearfog/Shitter/assets/34312687/d7603b7d-4381-44d5-8687-400b2c9f6782)

**Smartphone (please complete the following information):**
 - OS: Android 12 (e os 1.19.1)
 - App Version: 3.5.4

**Additional context**

**Comment by nuclearfog** [comment]
This area is used for replies. There must be space otherwise you can't swipe down to refresh.
