### ISSUE TITLE
Button behavior (REQUEST)

### ISSUE THREAD

**Issue by ItsRogueRen** [nuclearfog/Shitter#71]
as it stands the favorite and repost buttons do nothing on the timeline, and only activate when long-pressed. This is counterintuitive to every other social media app out there, and I would like to see it changed to tapping from the timeline or post activates, and a long-press shows the list of who has favorited/reposted/etc

Also less important but a setting to put tabs at the bottom would be nice

**Comment by nuclearfog** [comment]
This is intended to prevent accidentally reposting/favoriting a post. See: https://github.com/nuclearfog/Shitter/blob/master/CONTRIBUTING.md
